# Generated by Django 5.1 on 2024-08-25 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie', models.IntegerField()),
                ('protein', models.FloatField()),
                ('glucid', models.FloatField()),
                ('lipid', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('informations', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ingredient.nutritioninformation')),
            ],
        ),
    ]
