# Generated by Django 5.1 on 2024-08-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritioninformation',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='calorie',
            field=models.IntegerField(default=0),
        ),
    ]
