# Generated by Django 5.1 on 2024-08-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0005_alter_ingredient_informations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='informations',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='calorie',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='glucid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='lipid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='IngredientInformation',
        ),
    ]
