# Generated by Django 5.1 on 2024-08-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0006_remove_ingredient_informations_ingredient_calorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calorie',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
